config/routes.rb
Rails.application.routes.draw do
root to: 'occupants#index'

resources :occupants do
  resources :chores

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chore.rb
class Chore < ApplicationRecord
  belongs_to :occupant 
end

app/models/occupant.rb
class Occupant < ApplicationRecord
  has_many :chores, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/chores_controller.rb
class ChoresController < ApplicationController

def index
  @chores = Chore.all
end

def new
  @occupant = Occupant.find(params[:occupant_id])
  @chore = Chore.new
end


def create
  @occupant = Occupant.find(params[:occupant_id])
  @chore = Chore.create!(chore_params.merge(occupant: @occupant))
  redirect_to occupant_chore_path(@occupant, @chore)
end

def show
  @chore = Chore.find(params[:id])
end

def edit
  @chore = Chore.find(params[:id])
end

def update
  @chore = Chore.find(params[:id])
  @occupant = Occupant.find(params[:occupant_id])
  @chore.update(chore_params.merge(occupant: @occupant))
  redirect_to occupant_chore_path(@chore.occupant, @chore)
end

def destroy
  @chore = Chore.find(params[:id])
  @chore.destroy
  redirect_to chores_path
end

private
  def chore_params
    params.require(:chore).permit(:task, :description, :occupant_id)
  end
end

app/controllers/occupants_controller.rb
class OccupantsController < ApplicationController
  def index
    @occupants = Occupant.all
  end

  def new
    @occupant = Occupant.new
  end

  def create
    @occupant = Occupant.create!(occupant_params)

    redirect_to occupant_path(@occupant)
  end

  def show
    @occupant = Occupant.find(params[:id])
  end


  def edit
    @occupant = Occupant.find(params[:id])
  end

  
  def update
    @occupant = Occupant.find(params[:id])
    @occupant.update(occupant_params)

    redirect_to occupant_path(@occupant)
  end

  def destroy
    @occupant = Occupant.find(params[:id])
    @occupant.destroy

    redirect_to occupant_path(@occupant)
  end

  private
  def occupant_params
    params.require(:occupant).permit(:name, :age)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chores_helper.rb
module ChoresHelper
end

app/helpers/occupants_helper.rb
module OccupantsHelper
end

app/views/chores/_form.html.erb
<%= form_for([@occupant, @chore]) do |f| %>

  <%= f.label :task %>
  <%= f.text_field :task %>

  <%= f.label :description %>
  <%= f.text_field :description %>

  <%= f.submit %>

<% end %>

app/views/chores/edit.html.erb
<h2>Edit Chore</h2>

<form action="/chores/<%= @chore.id %>" method="post">
  <input type="hidden" name="_method" value="put">

  <label for="chore[task]">Task:</label>
  <input name="chore[task]" value="<%= @chore.task %>">


  <label for="chore[description]">Description:</label>
  <input name="chore[description]" value="<%= @chore.description %>">

  <input type="submit" value="CREATE">
</form>

<form action="/occupants/:occupant_id/chores/<%= @chore.id %>" method="delete">
  <input type="hidden" name="_method" value="delete">
  <input class="button-delete" type="submit" value="DELETE">
</form>

<br/>
<div class="buttons">
<button><%= link_to "BACK to Household Members", occupants_path %></button>
</div>

app/views/chores/new.html.erb
<h2>New Chore</h2>

<%= render 'form' %>

<br/>
<div class="buttons">
<button><%= link_to "BACK to Household Members", occupants_path %></button>
</div>

app/views/chores/show.html.erb
<h2>Task: <%= @chore.task %> <a href="/occupants/:occupant_id/chores/<%= @chore.id %> /edit">[EDIT task]</a></h2>
<h3>Name: <%= @chore.occupant.name %></h3>

<h4>Description: <%= @chore.description %><h4>
  <div class="buttons">
  <button><%= link_to "BACK to Household Members", occupants_path %></button>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ChoreGanizer</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <div class="intro">
    <h1><%= link_to "The Chore-ganizer", occupants_path %> </h1>
    <h2>Organize Your Household Chores!</h2>
  </div>
    <%= yield %>
  </body>
</html>

app/views/occupants/_form.html.erb
<%= form_for @occupant do |f| %>

  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :age %>
  <%= f.text_field :age %>

  <%= f.submit %>
  <% end %>

app/views/occupants/edit.html.erb
<h2>EDIT Household Member</h2>

<%= render "form" %>

  <br/>
<div class="buttons">
  <button><%= link_to "BACK to Household Members", occupants_path %></button>
</div>

app/views/occupants/index.html.erb
<h3>Household Members</h3>

<ul>
  <% @occupants.each do |occupant| %>
    <li>
      <%= link_to "Name: " + occupant.name, occupant %> -
      <%= link_to "Age: " + occupant.age, occupant %>
    </li>
  <% end %>
</ul>
<div class="buttons">
<button><%= link_to "Add a NEW Household Member", new_occupant_path %></button>
</div>

app/views/occupants/new.html.erb
<h2>Add NEW Household Member</h2>

<%= render "form" %>

  <br/>
  <div class="buttons">
    <button><%= link_to "BACK to Household Members", occupants_path %></button>
  </div>

app/views/occupants/show.html.erb
<h2><%= "Name: " + @occupant.name %></h2>
<h2><%= "Age: " + @occupant.age %></h2>
<br/>
<h3>Chores</h3>
<ul>
  <% @occupant.chores.each do |chore| %>
    <li>
      <p><%= link_to "Task: #{chore.task} | Description: #{chore.description}", occupant_chore_path(@occupant, chore) %></p>
    </li>
  <% end %>
</ul>

<br/>
<div class="buttons">
<button><%= link_to "EDIT Household Member " + @occupant.name, edit_occupant_path(@occupant) %></button>
<button><%= link_to "DELETE Household Member " + @occupant.name, occupant_path(@occupant),
method: :delete,
data: { confirm: "Are you CERTAIN?" } %></button>
<br/>
<br/>
<button><%= link_to "BACK to Household Members", occupants_path %></button>
</div>